Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: '2010-09-09'
Description: Step Functions workflow to process documents and generate vector embeddings using Amazon Bedrock with automated database setup

Parameters:
  RawPrefix:
    Type: String
    Default: raw/
  CleanedPrefix:
    Type: String
    Default: cleaned/
  CuratedPrefix:
    Type: String
    Default: curated/
  ChunkSize:
    Type: String
    Default: '3000'
    Description: in bytes
  ChunkOverlap:
    Type: String
    Default: '300'
    Description: in bytes
  DatabaseName:
    Type: String
    Default: mydb
    Description: The name of the database
  TableName:
    Type: String
    Default: vectortable
    Description: The name of the table to store text and vector data
  EmbeddingModelId:
    Type: String
    Default: amazon.titan-embed-text-v2:0
    Description: The ID of the embedding model to use
  EmbeddingModelType:
    Type: String
    Default: bedrock
    Description: model service
    AllowedValues:
    - bedrock
    - sagemaker
  DatabaseUsername:
    Type: String
    Default: Auser123_45
    NoEcho: true
    Description: The username for the Serverless Aurora PostgreSQL cluster
  DatabasePassword:
    Type: String
    NoEcho: true
    Description: The password for the Serverless Aurora PostgreSQL cluster
  WorkspaceId:
    Type: String
    Default: vectordb
    Description: The ID of the workspace

Resources:
  # VPC and Networking Resources
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-igw

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Create subnets in different AZs
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select 
        - 0
        - !GetAZs !Ref AWS::Region
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-subnet-1

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select 
        - 1
        - !GetAZs !Ref AWS::Region
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-subnet-2

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-route-table

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1
      RouteTableId: !Ref RouteTable

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet2
      RouteTableId: !Ref RouteTable

  # Security Groups
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for RDS database with restricted access"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
          Description: "Allow Lambda functions to access RDS on PostgreSQL standard port"
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16
          Description: "Allow PostgreSQL outbound traffic within VPC"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-db-sg

  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for Lambda functions with restricted access"
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: "Allow HTTPS traffic for AWS services"
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16
          Description: "Allow PostgreSQL access within VPC"
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-lambda-sg

  # Database Resources
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for vectorization database
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-db-subnet-group

  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "KMS key for encrypting resources"
      EnableKeyRotation: false
      PendingWindowInDays: 7
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: "Allow RDS to use the key"
            Effect: Allow
            Principal:
              Service: 'rds.amazonaws.com'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
          - Sid: "Allow Lambda to use the key"
            Effect: Allow
            Principal:
              Service: 'lambda.amazonaws.com'
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
      Tags:
        - Key: Purpose
          Value: "Database and Secret Encryption"

  VectorDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: '15.4'
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Ref DatabaseUsername
      MasterUserPassword: !Ref DatabasePassword
      DBClusterIdentifier: !Sub ${AWS::StackName}-db
      EnableHttpEndpoint: true
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 1
      StorageEncrypted: true
      KmsKeyId: !GetAtt KMSKey.Arn
      BackupRetentionPeriod: 7
      DeletionProtection: false
      CopyTagsToSnapshot: true
      EnableIAMDatabaseAuthentication: true
      DBClusterParameterGroupName: !Ref ClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
      EnableCloudwatchLogsExports:
        - postgresql
      PreferredBackupWindow: "03:00-04:00"
      PreferredMaintenanceWindow: "mon:04:00-mon:05:00"

  VectorDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref VectorDBCluster
      StorageEncrypted: true
      DBInstanceClass: db.serverless
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      AutoMinorVersionUpgrade: true
      DeletionProtection: false
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      EnableCloudwatchLogsExports:
        - postgresql

  ClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Parameter group for Aurora PostgreSQL
      Family: aurora-postgresql15
      Parameters: 
        max_wal_senders: "20"
        rds.force_ssl: "1"

  DBPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}-db-password
      Description: Password for vectorization database
      KmsKeyId: !GetAtt KMSKey.Arn
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DatabaseUsername}"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  # Secret rotation removed for demo purposes - not required for development/testing

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - !Ref LambdaS3Policy
        - !Ref LambdaBedrockPolicy
        - !Ref LambdaRDSPolicy
        - !Ref LambdaSecretPolicy

  # Custom managed policies for Lambda
  LambdaS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Minimal S3 policy for Lambda document processing"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Sub "${ContentBucket}/*"
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource: !Ref ContentBucket

  LambdaBedrockPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy for Lambda Bedrock access"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/${EmbeddingModelId}

  LambdaRDSPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy for Lambda RDS access"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - rds-data:ExecuteStatement
              - rds-data:BatchExecuteStatement
            Resource: !GetAtt VectorDBCluster.DBClusterArn

  LambdaSecretPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy for Lambda Secrets Manager access"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Ref DBPasswordSecret

  # Lambda Functions
  DatabaseInitFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/DatabaseInitFunction/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 256
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          CLUSTER_ARN: !GetAtt VectorDBCluster.DBClusterArn
          SECRET_ARN: !Ref DBPasswordSecret
          DATABASE_NAME: !Ref DatabaseName
          TABLE_NAME: !Ref TableName
      Description: This function initializes the PostgreSQL database with pgvector extension and required tables
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref Subnet1
          - !Ref Subnet2

  GetByteRangesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/GetByteRangesFunction
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          CHUNK_SIZE: !Ref ChunkSize
          CHUNK_OVERLAP: !Ref ChunkOverlap
          PYTHONPATH: /opt/python
      Layers:
        - !Ref SharedLibrariesLayer

  IngestDocFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/IngestDocFunction
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          PYTHONPATH: /opt/python
      Layers:
        - !Ref SharedLibrariesLayer

  IngestPDFFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/IngestPDFFunction
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          PYTHONPATH: /opt/python
      Layers:
        - !Ref SharedLibrariesLayer

  IngestTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/IngestTextFunction
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          PYTHONPATH: /opt/python
      Layers:
        - !Ref SharedLibrariesLayer

  VectorizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/VectorizeFunction
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          EMBEDDING_MODEL_ID: !Ref EmbeddingModelId
          EMBEDDING_MODEL_TYPE: !Ref EmbeddingModelType
          PYTHONPATH: /opt/python
      Layers:
        - !Ref SharedLibrariesLayer

  # Shared Libraries Layer
  SharedLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-libraries
      Description: Common libraries for document processing
      ContentUri: functions/shared
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain

  # S3 Bucket for content storage
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-content-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "aws:kms"
              KMSMasterKeyID: !GetAtt KMSKey.Arn
      NotificationConfiguration:
        QueueConfigurations:
        - Event: s3:ObjectCreated:*
          Filter:
            S3Key:
              Rules:
              - Name: prefix
                Value: raw/
          Queue: !GetAtt DocumentQueue.Arn
    DependsOn:
    - DocumentQueuePolicy

  # SQS Queue for document processing
  DocumentQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-document-queue
      MessageRetentionPeriod: 1209600
      KmsMasterKeyId: !GetAtt KMSKey.Arn

  DocumentQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DocumentQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt DocumentQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub arn:aws:s3:::${AWS::StackName}-content-${AWS::AccountId}

  # Step Functions State Machine
  DocumentProcessingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${AWS::StackName}-document-processing
      DefinitionUri: statemachine.json
      DefinitionSubstitutions:
        IngestTextFunction: !GetAtt IngestTextFunction.Arn
        IngestPDFFunction: !GetAtt IngestPDFFunction.Arn
        IngestDocFunction: !GetAtt IngestDocFunction.Arn
        GetByteRangesFunction: !GetAtt GetByteRangesFunction.Arn
        VectorizeFunction: !GetAtt VectorizeFunction.Arn
      Role: !GetAtt StepFunctionsRole.Arn
      Events:
        SQSEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Input: !Sub |
              {
                "QueueUrl": "${DocumentQueue}"
              }

  # Step Functions execution role
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt IngestTextFunction.Arn
                  - !GetAtt IngestPDFFunction.Arn
                  - !GetAtt IngestDocFunction.Arn
                  - !GetAtt GetByteRangesFunction.Arn
                  - !GetAtt VectorizeFunction.Arn

Outputs:
  ContentBucketName:
    Description: Name of the S3 bucket for content storage
    Value: !Ref ContentBucket
    Export:
      Name: !Sub ${AWS::StackName}-ContentBucket

  DatabaseClusterArn:
    Description: ARN of the Aurora PostgreSQL cluster
    Value: !GetAtt VectorDBCluster.DBClusterArn
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseClusterArn

  StateMachineArn:
    Description: ARN of the Step Functions state machine
    Value: !Ref DocumentProcessingStateMachine
    Export:
      Name: !Sub ${AWS::StackName}-StateMachine

  DatabaseSecretArn:
    Description: ARN of the database password secret
    Value: !Ref DBPasswordSecret
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseSecret