AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'emit-and-wait

  Sample SAM Template for emit-and-wait

  '
Resources:
  StateMachineArn:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri:
        Bucket: da-public-assets
        Key: workflows/a62dc885ef785bd544e7a614a6d9fceb
      Policies:
      - EventBridgePutEventsPolicy:
          EventBusName: Default
    Metadata:
      SamResourceId: StateMachineArn
Outputs:
  StateMachineArn:
    Description: state machine ARN
    Value:
      Ref: StateMachineArn
